version: 0.2

env:
  variables:
    ImageName: simple-docker-service

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 932117064429.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ImageName -f simple-python-app/Dockerfile simple-python-app/
  post_build:
    commands:
      - echo Build completed on `date`
      - docker tag $ImageName:latest 932117064429.dkr.ecr.us-east-1.amazonaws.com/$ImageName:latest
      - docker push 932117064429.dkr.ecr.us-east-1.amazonaws.com/$ImageName:latest
